"""Add file_path to Game

Revision ID: 15dee166b5ad
Revises: 712eb8faa5d8
Create Date: 2025-10-29 09:28:05.091329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15dee166b5ad'
down_revision = '712eb8faa5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('developer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('developer')
        batch_op.drop_column('size')
        batch_op.drop_column('platform')
        batch_op.drop_column('genre')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###
