"""Add Wompi transaction_ref and status to Donation

Revision ID: 712eb8faa5d8
Revises: 25bd356758eb
Create Date: 2025-10-17 08:59:13.236080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712eb8faa5d8'
down_revision = '25bd356758eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['transaction_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('transaction_ref')

    # ### end Alembic commands ###
